### ISSUE TITLE
Curious about the values of the sigma

### ISSUE THREAD

**Issue by andrewliao11** [Kaixhin/NoisyNet-A3C#6]
Hi @Kaixhin 
I wonder if the sigma in NoisyNet-A3C will fast shrink to nearly zero or not.
since if the values of the sigma is nearly zero, no exploration will be done by the agent.
The reason why I ask this is that [NoisyNet-DQN seems to shrink to zero after 2M steps](https://github.com/andrewliao11/NoisyNet-DQN#the-decreasing-sigma) and I want to know whether it happened in A3C version.

**Comment by Kaixhin** [comment]
On a poor run (similar to the second run in my readme), I saw sigma go slightly done for the actor and slightly up for the critic. Same for a good run, except for both biases shrunk a bit. Either way, it's within an order of magnitude. This is an LSTM A3C, which wasn't covered in the paper, and the domain is CartPole, which is very different to Atari, so I wouldn't draw any conclusions from this.

I've adjusted the code to print these values, so you can try running it yourself and see what happens.
