### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by jvmncs** [Kaixhin/NoisyNet-A3C#7]
How many runs you went through to come up with min/max/mean stats for the plots in README.md?  I'm looking into implementing NoisyNet-A3C for a particular use case and I'm wondering how feasible it will be on my machine.

**Comment by Kaixhin** [comment]
I currently evaluate over 10 episodes per evaluation in a single run. There is an `--evaluation-episodes` option in the code that allows you to configure this. None of the plots are calculated over several runs/seeds, which is why I instead put up a few plots for NoisyNet-A3C.
